#!/bin/sh
##
xfd=${X_FONT_DIR-/usr/local/lib/X11/fonts}
for subd in Droid webfonts URW profont; do
  [ -d ${xfd}/${subd} ] && xset +fp ${xfd}/${subd}/
done
xset fp rehash
xrdb -merge $HOME/.Xdefaults
xmodmap $HOME/.xmodmaprc
xsetroot -solid black
xscreensaver &
#fbpanel &
openbox
#mate-session
