#!/bin/sh
##
gsfd=${GS_FONT_DIR-/usr/local/share/ghostscript/fonts}
xfd=${X_FONT_DIR-/usr/local/lib/X11/fonts}
for subd in Droid webfonts URW profont mscorefonts; do
  [ -d ${xfd}/${subd} ] && xset +fp ${xfd}/${subd}/
done
[ -d ${gsfd} ] && xset +fp ${gsfd}/
xset fp rehash
xrdb -merge $HOME/.Xdefaults
xmodmap $HOME/.xmodmaprc
xsetroot -solid black
xscreensaver &
osdhud -Cwn -i em0
cwm
